# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

source 'git@bitbucket.org:goopterandriod/goopterplacepickerpodsec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GoopterBiz' do
  
  pod 'OAuthSwiftAlamofire', '~> 0.2.0'
  pod 'AlamofireObjectMapper', '~> 5.2.1'
  pod 'Alamofire', '~> 4.8.2'
  pod 'Cloudinary', '~> 2.8.0'
  pod 'SDWebImage', '~> 4.4.8'
  pod 'Charts', '~> 3.3.0'
  pod 'GooglePlaces', '~> 3.8.0'
  pod 'GoogleMaps', '~> 3.8.0'
  pod 'PhoneNumberKit', '~> 2.6.0'
  pod 'SideMenu', '~> 5.0.3'
  pod 'SwiftLint', '~> 0.39.1'
  pod 'CropViewController', '~> 2.5.2'
  pod 'RichEditorView', :git => 'https://github.com/cbess/RichEditorView.git', :branch => 'wkwebview'
  pod 'CocoaAsyncSocket', '~> 7.6.4'
  pod 'MMLanScan', '~> 3.0.0'
  pod 'GoopterPlacePicker', :git => 'git@bitbucket.org:goopterandriod/goopterplacepicker.git'
  pod 'BugfenderSDK', '~> 1.10.0'
  pod 'PusherSwift', '~> 8.0.0'
  pod 'SquareInAppPaymentsSDK', '~> 1.3.0'
  pod 'Firebase/Crashlytics'

  # pod 'StarIO', '~> 2.8.2'
  # pod 'StarIO_Extension', '~> 1.15.0'
  # pod 'SMCloudServices', '~> 1.5.1'
  # pod 'StarIODeviceSetting', '~> 1.0.0'

# pods for React Native
  pod 'FBLazyVector', :path => "./ReactNative/node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "./ReactNative/node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "./ReactNative/node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "./ReactNative/node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => './ReactNative/node_modules/react-native/'
  pod 'React-Core', :path => './ReactNative/node_modules/react-native/'
  pod 'React-CoreModules', :path => './ReactNative/node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => './ReactNative/node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => './ReactNative/node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => './ReactNative/node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => './ReactNative/node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => './ReactNative/node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => './ReactNative/node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => './ReactNative/node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => './ReactNative/node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => './ReactNative/node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => './ReactNative/node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => './ReactNative/node_modules/react-native/'

  pod 'React-cxxreact', :path => './ReactNative/node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => './ReactNative/node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => './ReactNative/node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => './ReactNative/node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "./ReactNative/node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "./ReactNative/node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => './ReactNative/node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => './ReactNative/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => './ReactNative/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => './ReactNative/node_modules/react-native/third-party-podspecs/Folly.podspec'
end

post_install do |installer|
  ## Fix for XCode 12.5
  find_and_replace("ReactNative/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
  "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
  find_and_replace("ReactNative/node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
  "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
    text = File.read(name)
    replace = text.gsub(findstr,replacestr)
    if text != replace
      puts "Fix: " + name
      File.open(name, "w") { |file| file.puts replace }
      STDOUT.flush
    end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      if ["Cloudinary", "SideMenu", "CropViewController"].include? target.name
#        config.build_settings['SWIFT_VERSION'] = '4.0'
#      end
#    end
#  end
#end
